/** GitHub release metadata is English; translated project guides remain separate. */
export function releaseNotes(
  sources,
  { draft = false, anonymous = false } = {},
) {
  const preview = sources.version.includes("-rc.");
  const catalog = preview ? "chess-coach-preview" : "chess-coach";
  const branch = preview ? "marketplace-preview" : "marketplace";
  return `Chess Coach ${sources.version}\n\n${preview ? "Preview release" : "Stable release"}${draft ? " candidate. Channel promotion is pending." : "."}\n\nPlay Stockfish on a local interactive board and discuss the actual position in Codex. The board supports English and Simplified Chinese. MCP, Stockfish, and saved games run on your computer.\n\n## Requirements\n\n- Linux x64, macOS Intel, or macOS Apple Silicon.\n- Node.js 26+ available on the Codex PATH.\n- Codex with plugin support; verified baseline: CLI 0.154.0.\n\nThe complete package contains the frontend, local MCP, Stockfish 18.0.8 JS/WASM, skills, logo, dependency licenses, and corresponding engine source. Users need no build step, project dependencies, Python, or flock.\n\n## Installation\n\n${draft ? "Use these commands after this draft is promoted:\n\n" : ""}\x60\x60\x60bash\ncodex plugin marketplace add jovijovi/chess-coach --ref ${branch}\ncodex plugin add chess-coach@${catalog}\n\x60\x60\x60\n\nStart a new Codex task and ask to open the chessboard. For manual upgrades, refresh the marketplace and reinstall:\n\n\x60\x60\x60bash\ncodex plugin marketplace upgrade ${catalog}\ncodex plugin add chess-coach@${catalog}\n\x60\x60\x60\n\nFor migration from the personal plugin, removal, and data-preserving rollback, see the [English guide](https://github.com/jovijovi/chess-coach/blob/main/README.md) or [Chinese guide](https://github.com/jovijovi/chess-coach/blob/main/README.zh-CN.md).\n\n## Validation\n\nNative Codex acceptance passed on all three platforms: eight MCP tools, ten full rounds each, offline local gameplay, position analysis, legal variations, restart, SSE, reinstallation, and PGN replay. Browser checks cover both UI languages. See the attached platform reports and checksums.\n\n${anonymous ? "Anonymous GitHub marketplace installation and subsequent offline native acceptance also passed.\n\n" : ""}Native checks use CLI/app-server APIs and real engine results. Signed-in desktop model conversations were not run on every platform; the automated checks validate the position and analysis supplied to the conversation.\n\n## Provenance and licenses\n\n- Source commit: ${sources.sourceCommit}\n- Runtime build ID: ${sources.buildId}\n- Immutable distribution reference: plugin-v${sources.version}\n- Original project: Apache-2.0. Stockfish retains GPL-3.0.\n\nOriginal artifacts are covered by SHA256SUMS. Additional acceptance attachments, when present, have a separate checksum file.\n`;
}
